<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ch.malbera.notification.service.NotificationServiceImplTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2018-02-12T22:53:42" hostname="malbera" time="0.033">
  <properties/>
  <testcase name="shouldSendBackupNotificationsEvenWhenErrorsOccursForSomeRecipients" classname="ch.malbera.notification.service.NotificationServiceImplTest" time="0.021"/>
  <testcase name="shouldSendRemindNotificationsEvenWhenErrorsOccursForSomeRecipients" classname="ch.malbera.notification.service.NotificationServiceImplTest" time="0.011"/>
  <system-out><![CDATA[2018-02-12 23:53:42.488  INFO 2377 --- [    Test worker] c.m.n.service.NotificationServiceImpl    : found 2 recipients for backup notification
2018-02-12 23:53:42.501 ERROR 2377 --- [onPool-worker-2] c.m.n.service.NotificationServiceImpl    : an error during backup notification for Recipient{accountName='with-error', email='null'}

java.lang.RuntimeException: null
	at ch.malbera.notification.service.NotificationServiceImpl.lambda$null$0(NotificationServiceImpl.java:40) ~[main/:na]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_161]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_161]

2018-02-12 23:53:42.503  INFO 2377 --- [    Test worker] c.m.n.service.NotificationServiceImpl    : found 2 recipients for remind notification
2018-02-12 23:53:42.511 ERROR 2377 --- [onPool-worker-1] c.m.n.service.NotificationServiceImpl    : an error during remind notification for Recipient{accountName='with-error', email='null'}

java.lang.RuntimeException: null
	at ch.malbera.notification.service.NotificationServiceImpl.lambda$null$2(NotificationServiceImpl.java:60) ~[main/:na]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[na:1.8.0_161]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_161]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_161]

]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
